### PR TITLE
fix gitian build scripts

### PR DESCRIPTION
**Pull request by erasmospunk**

### CODE REVIEW

**Comment by erasmospunk** [comment]
A quick update. The gitian windows build fails with DBD 5, but works with the older 4.8. Consider reverting to 4.8.

**Comment by ghost** [comment]
Reverting to 4.8 is not an option. It can't open existing wallets.

**Comment by janko33bd** [comment]
So what do I have to do, to build on windows now?

**Comment by xranby** [comment]
Can we upgrade to DBD 6.2.23 ? The latest release is designed to build on both 32bit and 64bit Windows. 

Configuration, Documentation, Sample Apps, Portability and Build Changes
7 . Added a 64-bit Windows binary release. [#24576]
http://download.oracle.com/otndocs/products/berkeleydb/html/changelog_6_2.html

**Comment by ghost** [comment]
There's a reason why I chose bdb5 instead of bdb6. Bdb6 has changed the
license to AGPL. If wallet links to bdb6 it also has to comply with
AGPL. This is not what an end user may expect.

**Comment by janko33bd** [comment]
Are you sure it applies to wallet too? 

AGPL provides the same restrictions and freedoms as the GPLv3 but with an additional clause which makes it so that source code must be distributed along with web publication. Since web sites and services are never distributed in the traditional sense, the AGPL is the GPL of the web.

**Comment by xranby** [comment]
@erasmospunk can you please file a new issue for the build error you observe on windows with DBD 5. Build errors are usually quite trivial to fix.

**Pull request merged**
